### PR TITLE
UI: Fix performance of getting subject models in Models Tree

### LINKED ISSUE #79: Hi, how do I determine the type of an element, thank you
Hi. I am using frontend to get an element with instanceId. May I ask how to determine whether this element is a graphical element or a non-graphical element? Or how to determine the type of element. I can't get information from ElementProps that I can judge? thank you
* * *

_⚠ Do not edit this section. It is required for imodeljs.github.io ➟ GitHub issue linking_

*   LINK: Getting-Started-With-iModel.js---iModel.js-link-to-docs
*   TAG: imodeljs-docs-question
*   SOURCE: https://www.imodeljs.org/getting-started//

### PR DESCRIPTION
**Pull request by grigasp**
Fixes itwin/itwinjs-backlog#79

Doing the join in a single query takes up to a minute in the problematic iModel. Doing 2 separate queries and joining them on the frontend takes up to 200 ms.

### CODE REVIEW

**Review by saskliutas — APPROVED** [review]

**Comment by grigasp** [comment]
@mergifyio backport release/3.2.x

**Review by bsteinbk — APPROVED** [review]

File: ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts [hunk 1]
```diff
@@ -419,43 +419,58 @@ class SubjectModelIdsCache {
...
+    const querySubjects = (): AsyncIterableIterator<{ id: Id64String, parentId?: Id64String, targetPartitionId?: Id64String }> => {
+      const subjectsQuery = `
+        SELECT ECInstanceId id, Parent.Id parentId, json_extract(JsonProperties, '$.Subject.Model.TargetPartition') targetPartitionId
+        FROM bis.Subject
+      `;
+      return this._imodel.query(subjectsQuery, undefined, { rowFormat: QueryRowFormat.UseJsPropertyNames });
+    };
+    const queryModels = (): AsyncIterableIterator<{ id: Id64String, parentId: Id64String, content?: string }> => {
+      const modelsQuery = `
+        SELECT p.ECInstanceId id, p.Parent.Id parentId, json_extract(p.JsonProperties, '$.PhysicalPartition.Model.Content') content
```
Comment (diegoalexdiaz) [inline ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts:432]: I've noticed that the "PhysicalPartition.Model.Content" Json name changes per type of Partition. That is, it can also be "SpatialLocationPartition.Model.Content" or "GeometricPartition3d.Model.Content". It seems the latter two will be missed by the "queryModels" ECSQL above.

I've also seen such piece of Json is not written by all connectors. At least the IFC and Revit connectors don't write it. Maybe only the dgn connectors do. It seems such piece of Json drives some "isHidden" attribute later on.

I believe we should revisit the reasons driving the introduction of such piece of Json and corresponding UX behaviors. Since it is not supported by all connectors, and it has problems with multiple kinds of partitions, it looks to be rather the source of bugs and inconsistencies in the UX.

cc: @grigasp

Comment (swwilson-bsi) [reply ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts:432]: IIRC The BIS working group recommended the current design. The goal was to add a hint to a Subject element so that presentation rules could know what it is for and how or if to display it. That was preferred to adding an IsPrivate or IsHidden property to the Subject class.

We only need presentation hints like this because connectors create Subjects that are not relevant to the user.

Comment (grigasp) [reply ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts:432]: > We only need presentation hints like this because connectors create Subjects that are not relevant to the user.

We have so many problems because of the fact that Subjects serve multiple purposes... And, sadly, it seems we're not going to have a concept that we could directly use for creating the hierarchy. Because of that, we have a project to remove the Subjects hierarchy from the Models Tree altogether. The project was on hold lately, I hope we can revive it soon.

Comment (grigasp) [reply ui/appui-react/src/appui-react/imodel-components/models-tree/ModelsVisibilityHandler.ts:432]: BTW, turns out querying the `PhysicalPartition.Model.Content` was unnecessary - here's a PR to remove it: #3697. 

It's still used when creating the hierarchy, though. There we use `PhysicalPartition.Model.Content` and `GraphicalPartition3d.Model.Content`. Now you're saying we're missing a few others with a possibility that there might be even more than that. Sounds like the list is not definite, because we'd get a new attribute every time a a new subclass of InformationPartitionElement is introduced.

@swwilson-bsi says that the sole purpose of this flag is to help create the Models Tree. Then I'd question what's the point of creating so many different attributes and making it difficult to capture all of them for the only component that uses them.

And just to explain what the attribute does in the Models Tree... When an InformationPartitionElement has this attribute, we don't show its Model node and instead show Categories directly under Subject node. So not capturing the attribute would mean the Model node **is** displayed.
