### PR TITLE
Synchronize SubCategoriesCache in read-write workflows

### LINKED ISSUE #8717: Stale Category Cache
**Describe the bug**
On the frontend, iModel.categories.getCategoryInfo(...) can be used to get category/sub-category information. If a sub-category's appearance is changed on the backend, additional calls to iModel.categories.getCategoryInfo(...) will continue to return the original color (and likely entire appearance) value for the rest of the session.

**To Reproduce**
- Open an iModel with some geometric elements
- Use iModel.categories.getCategoryInfo(...) to get the appearance of a sub-category of your choosing
- Update the sub-category element on the backend to have a different color
- Call iModel.categories.getCategoryInfo(...) again
- Observe that the color still shows the old value

**Expected behavior**
I expect the appearance value of any given sub-category to be up to date when calling iModel.categories.getCategoryInfo(...).

**Desktop (please complete the applicable information):**
- OS: Windows 11
- iTwin.js Versions 
Image

**Additional context**
Querying for the appearance directly with a query reader returns the correct result.

Calling iModel.categories.cache.clear() before subsequent calls to iModel.categories.getCategoryInfo(...) makes it return the correct result. 

Therefore, it seems likely that this frontend cache is not being invalidated when sub-categories get updated.

### PR DESCRIPTION
**Pull request by pmconne**
Fixes #8717.
If a category is deleted, invalidate its cache.
If a subcategory is updated or deleted, invalidate its parent category's cache.
If a subcategory is inserted, invalidate all categories' caches (we don't know to which category it belongs).

### CODE REVIEW

**Comment by pmconne** [comment]
@Mergifyio backport release/5.3.x

File: core/frontend/src/SubCategoriesCache.ts [hunk 1]
```diff
@@ -33,8 +33,46 @@ export class SubCategoriesCache {
...
+            // We don't know to which category the subcategory belongs. Blow away the entire cache.
+            this._byCategoryId.clear();
+            return;
+          }
+
+          affectedSubCategories.add(change.id);
+        }
+      }
 
+      if (affectedSubCategories.size > 0) {
```
Comment (MichaelSwigerAtBentley) [inline core/frontend/src/SubCategoriesCache.ts:65]: Do we also need to remove anything from the subCategory appearances list?

File: core/frontend/src/SubCategoriesCache.ts [hunk 2]
```diff
@@ -33,8 +33,46 @@ export class SubCategoriesCache {
   private readonly _imodel: IModelConnection;
   private _missingAtTimeOfPreload: Id64Set | undefined;
 
-  public constructor(imodel: IModelConnection) { this._imodel = imodel; }
+  public constructor(imodel: IModelConnection) {
+    this._imodel = imodel;
+  }
+
+  public attachToBriefcase(imodel: IModelConnection): void {
```
Comment (MichaelSwigerAtBentley) [inline core/frontend/src/SubCategoriesCache.ts:40]: Should we also look into clearing these caches if the attached briefcase has clearCaches() called?

File: core/frontend/src/SubCategoriesCache.ts (hunk 1 above)
Comment (pmconne) [reply core/frontend/src/SubCategoriesCache.ts:65]: Wow, yeah, how did I miss that.

File: core/frontend/src/SubCategoriesCache.ts (hunk 2 above)
Comment (pmconne) [reply core/frontend/src/SubCategoriesCache.ts:40]: No, this front-end cache is unrelated to the backend caches cleared by `IModelDb.clearCaches`.

File: core/frontend/src/SubCategoriesCache.ts (hunk 1 above)
Comment (pmconne) [reply core/frontend/src/SubCategoriesCache.ts:65]: Fixed.

**Review by danielzhong — APPROVED** [review]

**Review by markschlosseratbentley — APPROVED** [review]
👍

**Review by aruniverse — APPROVED** [review]
