### PR TITLE
fix deletion of elements in transformer during branch reverse synchronization 

### LINKED ISSUE #4072: IModelTransformer doesn't delete removed elements on reverseSynchronization
**Describe the bug**
IModelTransformer doesn't delete removed elements when `isReverseSynchronization` option is turned on and processChanges is called.

The cause of the bug is combination of two things:
1) In reverse synchronization ExternalSourceAspects are saved in source iModel.
2) Deleting element also removes its aspects.

This results in a case when IModelExporter detects deleted element, but IModelTransformer cannot delete it from target iModel because ExternalSourceAspect doesn't exist for deleted element in the source iModel.

**To Reproduce**
1. Create master iModel in iModelHub.
2. Populate master iModel with some elements.
3. Create branch iModel in iModelHub. This iModel should use master iModel as template.
4. Run IModelTransformer.processAll() with these options:
    - source iModel is master iModel
    - target iModel is branch iModel
    - `wasSourceIModelCopiedToTarget` is set to `true`
    - `noProvenance` is set to `false`
6. Pull changes for branch iModel.
7. Remove one element from branch iModel.
8. Push changes to iModelHub.
9. Run IModelTransformer.processChanges() with these options:
    - source iModel is branch iModel
    - target iModel is master iModel
    - `isReverseSynchronization` is set to true
10. Master iModel still has deleted element.

Here is a test case that reproduces the error (works in IModelTransformerHub.test.ts):
```ts
  const fillSnapshotSeed = (seed: SnapshotDb) => {
    const categoryId = SpatialCategory.insert(seed, IModel.dictionaryId, "Category1", {});
    const partitionProps: InformationPartitionElementProps = {
      classFullName: PhysicalPartition.classFullName,
      model: IModel.repositoryModelId,
      parent: new SubjectOwnsPartitionElements(IModel.rootSubjectId),
      code: PhysicalPartition.createCode(seed, IModel.rootSubjectId, "PhysicalPartition1"),
    };
    const partitionId = seed.elements.insertElement(partitionProps);

    const modelProps: GeometricModel3dProps = {
      classFullName: PhysicalModel.classFullName,
      modeledElement: { id: partitionId },
    };
    const modelId = seed.models.insertModel(modelProps);
    const element: GeometricElementProps = {
      classFullName: PhysicalObject.classFullName,
      model: modelId,
      category: categoryId,
      code: Code.createEmpty(),
      userLabel: "Element1",
    };
    const elementId = seed.elements.insertElement(element);
    return elementId;
  };

  it("should remove deleted elements in reverse synchronization", async () => {
    const masterIModelName = "Master";
    const masterSeedFileName = join(outputDir, `${masterIModelName}.bim`);
    if (IModelJsFs.existsSync(masterSeedFileName))
      IModelJsFs.removeSync(masterSeedFileName); // make sure file from last run does not exist

    const masterSeedDb = SnapshotDb.createEmpty(masterSeedFileName, { rootSubject: { name: "Master" } });
    // Save elementId for removal and assertions
    const elementId = fillSnapshotSeed(masterSeedDb);
    masterSeedDb.nativeDb.setITwinId(iTwinId); // WIP: attempting a workaround for "ContextId was not properly setup in the checkpoint" issue
    masterSeedDb.saveChanges();
    masterSeedDb.close();

    const masterIModelId = await IModelHost.hubAccess.createNewIModel({ iTwinId, iModelName: masterIModelName, description: "master", version0: masterSeedFileName, noLocks: true });
    assert.isTrue(Guid.isGuid(masterIModelId));
    IModelJsFs.removeSync(masterSeedFileName); // now that iModel is pushed, can delete local copy of the seed
    const masterDb = await HubWrappers.downloadAndOpenBriefcase({ accessToken, iTwinId, iModelId: masterIModelId });
    assert.isTrue(masterDb.isBriefcaseDb());
    assert.equal(masterDb.iTwinId, iTwinId);
    assert.equal(masterDb.iModelId, masterIModelId);

    // create Branch iModel using Master as a template
    const branchIModelName = "Branch";
    const branchIModelId = await IModelHost.hubAccess.createNewIModel({ iTwinId, iModelName: branchIModelName, description: `Branch of ${masterIModelName}`, version0: masterDb.pathName, noLocks: true });
    const branchDb = await HubWrappers.downloadAndOpenBriefcase({ accessToken, iTwinId, iModelId: branchIModelId });

    try {
      // Record provenance
      const provenanceInserter = new IModelTransformer(masterDb, branchDb, {
        wasSourceIModelCopiedToTarget: true,
        noProvenance: false,
      });
      await provenanceInserter.processAll();
      await saveAndPushChanges(branchDb, "State0");

      // Modifying branch
      const elementBeforeDeletion = branchDb.elements.tryGetElement(elementId);
      expect(elementBeforeDeletion).to.not.be.undefined;
      branchDb.elements.deleteElement(elementId);
      await saveAndPushChanges(branchDb, "State1");
      const elementAfterDeletion = branchDb.elements.tryGetElement(elementId);
      expect(elementAfterDeletion).to.be.undefined;

      // Merge back the changes
      const merger = new IModelTransformer(branchDb, masterDb, {
        isReverseSynchronization: true,
      });
      await merger.processChanges(accessToken, branchDb.changeset.id);
      await saveAndPushChanges(masterDb, "FinalState");

      // Assert
      const resultElement = masterDb.elements.tryGetElement(elementId);
      expect(resultElement).to.be.undefined;

    } finally {
      const masterDbId = masterDb.iModelId;
      const branchDbId = branchDb.iModelId;
      masterDb.close();
      branchDb.close();
      await IModelHost.hubAccess.deleteIModel({ iTwinId, iModelId: masterDbId });
      await IModelHost.hubAccess.deleteIModel({ iTwinId, iModelId: branchDbId });
    }
  });
```

**Expected behavior**
Deleted element in source iModel should be removed in target iModel when processing changes in reverse Synchronization.

**Desktop (please complete the applicable information):**

- OS: Windows
- Version 10
- iTwin.js Version 3.2.8

### PR DESCRIPTION
**Pull request by MichaelBelousov**
fixes #4072

- Extract element id remaps from deleted elements and their deleted ExternalSourceAspects using change summary ECSQL queries
- modify the existing branch tests to cover this case
- add a new test specific to this case that also covers model deletion
- Handle model deletes which the transformer previously did not do

I am going to add coverage for deleting relationships while processing changes in [reverse]synchronizations in the upcoming transform-non-element-entities work.

### CODE REVIEW

File: core/transformer/src/IModelImporter.ts [hunk 1]
```diff
@@ -272,6 +272,20 @@ export class IModelImporter implements Required<IModelImportOptions> {
...
+  /** Delete the specified Model from the target iModel.
+   * @note A subclass may override this method to customize delete behavior but should call `super.onDeleteModel`.
+   */
+  protected onDeleteModel(modelId: Id64String): void {
+    this.targetDb.models.deleteModel(modelId);
+    Logger.logInfo(loggerCategory, `Deleted model ${modelId}`);
+    this.trackProgress();
+  }
+
+  /** Delete the specified Element from the target iModel. */
```
Comment (pmconne) [inline core/transformer/src/IModelImporter.ts:284]: "Element" or "Model"?

Comment (MichaelBelousov) [reply core/transformer/src/IModelImporter.ts:284]: copy paste error, fixing

File: core/transformer/src/IModelTransformer.ts [hunk 2]
```diff
@@ -463,11 +473,75 @@ export class IModelTransformer extends IModelExportHandler {
 
   /** Initialize the source to target Element mapping from ExternalSourceAspects in the target iModel.
    * @note This method is called from [[processChanges]] and [[processAll]], so it only needs to be called directly when processing a subset of an iModel.
+   * @note Passing an [[InitFromExternalSourceAspectsArgs]] is required when processing changes, to remap any elements that may have been deleted.
+   *       You must await the returned promise as well in this case. The synchronous behavior has not changed but is deprecated and won't process everything.
    */
-  public initFromExternalSourceAspects(): void {
+  public initFromExternalSourceAspects(args?: InitFromExternalSourceAspectsArgs): Promise<void>;
```
Comment (pmconne) [inline core/transformer/src/IModelTransformer.ts:479]: Breaking change of return type from `void` to `Promise<void>` is ok because IModelTransformer is beta but please document in NextVersion.md.

Comment (pmconne) [reply core/transformer/src/IModelTransformer.ts:479]: Oh weird, your overload returns `void | Promise<void>`. Does that affect existing callers?

Comment (MichaelBelousov) [reply core/transformer/src/IModelTransformer.ts:479]: oh yes will add to NextVersoin.md, but it's not breaking, it still has an overload of void, it's just deprecated.
I did consider using beta to not have an overload but

**Review by pmconne — APPROVED** [review]

**Review by ColinKerr — APPROVED** [review]
