### PR TITLE
Fix slow unit tests after switch to i18n-http-backend

### LINKED ISSUE #4546: Fix slow unit tests after switch to i18n-http-backend
This was initially noticed by @raplemie - after #4250. 

When requests for localization resources fail, they are retried. After this PR, unit tests began to retry failed i18n requests. 
An easy fix for unit tests which do not need to test localizations is to use mocks (`EmptyLocalization` works)

### PR DESCRIPTION
**Pull request by mattbjordan**
Fixes #4546 

## Changes

Where possible, [EmptyLocalization](https://github.com/iTwin/itwinjs-core/blob/c849fcb7f8b41ed11b99f49e3137820094778598/core/common/src/Localization.ts#L111) is now used for localization in tests to increase test performance.

### Non-trivial Changes

- `EmptyLocalization.getLocalizedString` was changed to return values similar to what i18next's translation function would return.
- The "CommandLaunchBackstageItem renders correctly" test was slightly modified.
  - This was the **only** test case that required any changes. It still seems correct to me, but I may not fully understand it.
- The following test utility classes either now use EmptyLocalization entirely or by default while still allowing for an ITwinLocalization instance to be passed in instead when needed:
   - ui/core-react/src/test/TestUtils.ts 
   - ui/components-react/src/test/TestUtils.ts
   - full-stack-tests/presentation/src/IntegrationsTests.ts
   - presentation/testing/src/presentation-testing/Helpers.ts
   - core/frontend/src/NoRenderApp.ts
   - core/frontend/src/render/MockRender.ts

## Explanation

The reason for the performance decrease (noticed by @raplemie) after merging #4250 is that:

By default `IModelApp` attempts to register a few localization namespaces that may or may not exist ([code](https://github.com/iTwin/itwinjs-core/blob/26a8e81684432cd3cea195a86bbacdf79b7f5746/core/frontend/src/IModelApp.ts#L371)). In tests, **these namespaces typically don't exist**. Many tests initialize `IModelApp` meaning that each of those calls _also_ attempts to register the default localization namespaces. **Each initialization is adding approximately 350ms to the run time via localization retries.** 

An explanation of the retries:
1. i18next-http-backend will use fetch to look for and read from a localization resource (e.g., a file).
2. If that resource does not exist, an error is thrown.
3. If an error is thrown, i18next will go into a retry loop to request the resource again. We have set this to a max of one retry ([code](https://github.com/iTwin/itwinjs-core/blob/9ac1ecac8becae2603eb095c08130372415faddb/core/i18n/src/ITwinLocalization.ts#L15)).
4. There is a timeout which waits some time in between attempts. The first retry will happen 350ms after the error is thrown. (350ms is the default value.)

By switching to EmptyLocalization for any test that doesn't rely on localization, requests for a localization namespace can be skipped, thus removing the 350ms retry delays from each IModelApp initialization.

## Addendum 

I'd like to get these changes in for AppUI as @raplemie primarily noticed the time increases for appui tests and this will amend them. However, there is probably more to investigate.

When running appui tests by themselves, the time that they take is the same as they were before the performance decreased from swapping to i18next-http-backend. However, the time that they take when running via `rush cover` is still longer than before. E.g., via `rush cover`, @itwin/appui-abstract tests take ~18 seconds to run in release 3.3.5 and ~32 seconds to run as of this PR; yet to run the tests by themselves, they take the same amount of time on both versions.

This discrepancy could extend to other packages as well, so this should be investigated. A separate issue will be created (by me) to track this.

### CODE REVIEW

**Comment by mattbjordan** [comment]
> Wouldnt it be beneficial to update the MockRender.App.startup to simply add "EmptyLocalization" if none is provided?

Done. And yeah that's much better. EmptyLocalization is now the default for MockRender.App, but another Localization implementation can be passed in and used instead.

**Comment by raplemie** [comment]
> Done. And yeah that's much better. EmptyLocalization is now the default for MockRender.App, but another Localization implementation can be passed in and used instead.

Will you remove all the explicit `startup({localization: new EmptyLocalization})` ?

**Comment by mattbjordan** [comment]
> Will you remove all the explicit `startup({localization: new EmptyLocalization})` ?

I already did for all of the `MockRender.app.startup` calls. I can probably make the same change to `NoRenderApp.startup` calls by making EmptyLocalization the default in NoRenderApp, as long as that doesn't break too many other tests.

**Comment by raplemie** [comment]
> I already did for all of the `MockRender.app.startup` calls. I can probably make the same change to `NoRenderApp.startup` calls by making EmptyLocalization the default in NoRenderApp, as long as that doesn't break too many other tests.

Wow, my bad, I looked too fast! I didnt notice the MockRender vs NoRender in the test files while reviewing.

**Comment by mattbjordan** [comment]
> I can probably make the same change to `NoRenderApp.startup` calls by making EmptyLocalization the default in NoRenderApp, as long as that doesn't break too many other tests.

I was able to make this change without any issues.

**Review by ben-polinsky — APPROVED** [review]

**Review by raplemie — APPROVED** [review]
LGTM!

**Review by grigasp — APPROVED** [review]

File: core/common/src/Localization.ts [hunk 1]
```diff
@@ -110,7 +110,14 @@ export interface Localization {
...
 export class EmptyLocalization implements Localization {
   public async initialize(): Promise<void> { }
-  public getLocalizedString(key: string | string[]): string { return typeof (key) == "string" ? key : key[0]; }
+  public getLocalizedString(key: string | string[]): string {
+    if (typeof (key) !== "string") {
+      key = key[0];
+    }
+    // Simulate correct and simple usage of i18next's translation function
+    // Namely, remove the leading namespace substring if there is one
+    return key.split(":", 2).pop()!;
```
Comment (aruniverse) [inline core/common/src/Localization.ts:119]: just curious why make this change?

**Review by aruniverse — APPROVED** [review]
lgtm;

just curious do you have a rough estimate of how much faster now?
were you able to determine why `rushx cover` is taking longer than `npm run cover`? is there alot of overhead for rush to spawn the process or something?

please don't bother merging master into your branch unless there are conflicts. dont want to waste another ci run and sit here for another few hrs

File: core/common/src/Localization.ts (hunk 1 above)
Comment (mattbjordan) [reply core/common/src/Localization.ts:119]: This change fixes a problem that appeared when switching to using EmptyLocalization for tests. 

When there is no value for the given key, i18next returns the key without the leading namespace. E.g., `getLocalizedString("myNamespace:myKey")` would return `"myKey"` if the key didn't exist. Before this change, EmptyLocalization would've returned `"myNamespace:myKey"` because it was simply returning the string. Some tests relied on how i18next returned a value, so I made EmptyLocalization simulate it.

Comment (aruniverse) [reply core/common/src/Localization.ts:119]: was this an issue with snapshots?

**Comment by mattbjordan** [comment]
> just curious do you have a rough estimate of how much faster now? is there alot of overhead for rush to spawn the process or something?

Here are some times from running the tests individually, i.e., running `npm run cover` from within their directory. The times from before the i18next-http-backend change are represented by Release 3.3.5. All times are in seconds.

```+----------------------------------------------------+---------------+-------------------+-----+
|                      Package                       | Release 3.3.5 | Before PR Changes | Now |
+----------------------------------------------------+---------------+-------------------+-----+
| appui-react                                        |            29 |               180 |  36 |
| components-react                                   |            22 |                60 |  23 |
| core-react                                         |             7 |                17 |  15 |
| imodel-components-react                            |            20 |                31 |  21 |
| presentation-full-stack-tests (rounded to minutes) |           120 |               420 | 120 |
+----------------------------------------------------+---------------+-------------------+-----+
```

This PR largely gets the times back down to what they were before. Now ~= Release 3.3.5. However, there is still some investigation to be done. The times from running `rush cover` are still worse than before and I'm not sure why- though, much better because of this PR! I'm working on getting some good data to show and use before I create another to track this (should be soon).

>  were you able to determine why `rushx cover` is taking longer than `npm run cover`?

Seems like [`rushx cover` is equivalent to `npm run cover`](https://rushjs.io/pages/developer/everyday_commands/#rushx) so there was no difference.

**Comment by raplemie** [comment]
Core react changes may be due to moving from enzyme to react testing library, many components were not really run at all with enzyme while they are now fully rendered and some inputs (using user-events) are now fully rendered, so that likely had an effect on timing. There may be other stuff there too however. (Notice that in itwinjs-core, the other packages were not udpated to rtl as this change was made in appui repo only, so that fits what we see)

More than double the time is something I will probably want to look into though, but given the number of changes in core-react in appui, the times will no longer be comparable given the number of components that were removed (deprecated stuff)

**Comment by raplemie** [comment]
#4270 likely explaing the timing difference in `appui-react`.

**Comment by mattbjordan** [comment]
> Core react changes may be due to moving from enzyme to react testing library

Ah, probably worth mentioning that the testing I did doesn't account for any added tests or changes to tests between release 3.3.5 and this PR. So it's good to hear that there may be a reason for why core-react didn't improve as much with the EmptyLocalization.
