### PR TITLE
Fix AccuDraw UI colors

### LINKED ISSUE #8956: Floating Accudraw fields lacks contrast. Especially in light theme.
When the application is in light theme, the un-focused accudraw input field is not readable or not visible : 
Text is not readable : 
Image
Locked icon is not visible :
Image

Looking at the code, for the text, the white color variable is used : https://github.com/iTwin/itwinjs-core/blob/6d0026ffd033884ab441714833cbd9922059283a/core/frontend/src/tools/AccuDrawViewportUI.ts#L75

We should revise the varibles used to get the fields adjust depending on the theme used (dark/light).
Example, for the text, I suggest using --iui-color-text or --iui-color-text-disabled to get better results : 
Image
Image

Thanks

### PR DESCRIPTION
**Pull request by carlos-menezes**
Closes #8956

iTwin Studio (light/dark):
image 
image

`display-test-app`
image

### CODE REVIEW

**Comment by carlos-menezes** [comment]
@bbastings Unchanged from our changes a few months ago:

image

**Comment by bbastings** [comment]
> @bbastings Unchanged from our changes a few months ago:

Yeah, was wondering how it looked on light theme though, will assume you tried it and it was acceptable. :)

**Review by markschlosseratbentley — APPROVED** [review]
LGTM

File: core/frontend/src/tools/AccuDrawViewportUI.ts [hunk 1]
```diff
@@ -664,7 +666,13 @@ export class AccuDrawViewportUI extends AccuDraw {
         break;
       case false:
         style.backgroundColor = controlProps.input.unfocused.backgroundColor;
-        style.outline = "none";
+        /**
+         * StrataKit resets the `outline` style here: https://github.com/iTwin/stratakit/blob/d08ecb28ca4e304094489522eb8e17c9a10865b3/packages/foundations/src/~unlayered.css#L10
+         * This causes the input to have a white outline (which doesn't match the Figma design) when focused unless we override it again with `!important`.
```
Comment (anmolshres98) [inline core/frontend/src/tools/AccuDrawViewportUI.ts]:
```suggestion
         * This causes the input to have a white outline when focused unless we override it again with `!important`.
```
I don't think this is necessary

Comment (carlos-menezes) [reply core/frontend/src/tools/AccuDrawViewportUI.ts]: Removed.

**Comment by bbastings** [comment]
Does this need a backport? @mathieu-fournier

**Comment by mathieu-fournier** [comment]
> Does this need a backport? @mathieu-fournier

I dont think so, we released in prod some days ago and a backport would need to also be consumed by studio. We'll wait for studio to consume it first. Thanks for awsking.
