### PR TITLE
Prerelease version type choices added for versionDb command of workspace cli utility

### LINKED ISSUE #7070: WorkspaceEditor cli utility does not support prerelease choices for versionDb command
**Describe the bug**
Recently we have added support for pre-release workspace db creation. However, when we try to version that prerelease workspace db using `versionDb ` command, it won't work. 

**To Reproduce**

1. Create a new workspace db using `createDb` command
2. Try to create new prerelease version of same db using `versionDb` command.
`WorkspaceEditor versionDb styles --versionType prerelease`
It will show below error.
image

**Expected behavior**
`versionDb` command should have choice of prerelease version type.

**Screenshots**
image

**Desktop (please complete the applicable information):**

- OS: Windows 11 
- iTwin.js Version [4.8.x]

### PR DESCRIPTION
**Pull request by YashodipD**
Fixes #7070

### CODE REVIEW

File: utils/workspace-editor/src/WorkspaceEditor.ts [hunk 1]
```diff
@@ -666,7 +666,7 @@ Yargs.command<MakeVersionOpt>({
   command: "versionDb <dbName>",
   describe: "make a new version of a WorkspaceDb",
   builder: {
-    versionType: { describe: "the type of version to create", default: "patch", string: true, choices: ["major", "minor", "patch"] },
+    versionType: { describe: "the type of version to create", default: "patch", string: true, choices: ["major" , "minor" , "patch" , "premajor" , "preminor" , "prepatch" , "prerelease"] },
```
Comment (YashodipD) [inline utils/workspace-editor/src/WorkspaceEditor.ts:669]: should we update default ?

**Review by pmconne — APPROVED** [review]
